apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: llm-secure-inference
spec:
  podSelector:
    matchLabels:
      app: llm-secure-inference
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8001
