apiVersion: v1
kind: Service
metadata:
  name: llm-secure-inference
  labels:
    app: llm-secure-inference
spec:
  selector:
    app: llm-secure-inference
  ports:
    - name: http
      port: 80
      targetPort: http
