apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-secure-inference
  labels:
    app: llm-secure-inference
spec:
  selector:
    matchLabels:
      app: llm-secure-inference
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
